# Form implementation generated from reading ui file 'main-view.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(915, 579)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(150, 530, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(110, 440, 161, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 440, 161, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(660, 440, 161, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.subject_url = QtWidgets.QLineEdit(parent=Dialog)
        self.subject_url.setGeometry(QtCore.QRect(30, 40, 271, 31))
        self.subject_url.setObjectName("subject_url")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 130, 641, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(40, 10, 161, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 201, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(390, 170, 201, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(90, 210, 421, 211))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(540, 210, 341, 211))
        self.label_5.setObjectName("label_5")
        self.verticalScrollBar_3 = QtWidgets.QScrollBar(parent=Dialog)
        self.verticalScrollBar_3.setGeometry(QtCore.QRect(470, 230, 16, 160))
        self.verticalScrollBar_3.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar_3.setObjectName("verticalScrollBar_3")
        self.verticalScrollBar = QtWidgets.QScrollBar(parent=Dialog)
        self.verticalScrollBar.setGeometry(QtCore.QRect(840, 230, 16, 160))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Launch"))
        self.pushButton_2.setText(_translate("Dialog", "Deep Probe"))
        self.pushButton_3.setText(_translate("Dialog", "View Images"))
        self.subject_url.setPlaceholderText(_translate("Dialog", "wikipedia.org/wiki/YourFavoriteStar"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "TYPE or DROP your search terms here; use csv or txt file if it\'s a long list."))
        self.label.setText(_translate("Dialog", "Subject"))
        self.label_2.setText(_translate("Dialog", "Search Terms"))
        self.label_3.setText(_translate("Dialog", "wikiSpyder 0.3.1"))
        self.label_4.setText(_translate("Dialog", "TextLabel"))
        self.label_5.setText(_translate("Dialog", "TextLabel"))
